### ISSUE TITLE
Error Message ：Illegal Characters in Path

### ISSUE THREAD

**Issue by ArtHuge** [HakuSystems/EasyExtractUnitypackage#3]
The unpacked resource may contain illegal character paths.

**Comment by HakuSystems** [comment]
Hi [[ArtHuge](https://github.com/ArtHuge)],

Thank you for reporting this issue with EasyExtractUnitypackage. To help us better understand and address the problem, could you please fill out the following details:

**Describe the bug**  
A clear and concise description of what the bug is. Please include any specific error messages you encountered.

**Steps to reproduce**  
To help us replicate the issue on our end, please provide detailed steps:<
Example:
1. Open the application.
2. Perform [specific action].
3. Encounter the error.

**Expected behavior**  
Describe what you expected to happen when you followed the steps mentioned above.

**Screenshots**  
If possible, add screenshots to help explain the issue. This can be very helpful in visualizing the problem.

**Environment (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]
- Version: [application version]

**Additional context**  
Any other context or details you think might help us understand the issue better.

Once you provide this information, we'll be better equipped to tackle the problem more efficiently.

Looking forward to your reply,

**Comment by HakuSystems** [comment]
We Fixed it! try our new version.

## Version 2.0.5.8 - 20.07.2024

**Bug Fix: Invalid Path Syntax in Unity Package Extraction**

**Issue:**  
Users encountered an error stating "The file name, directory name, or volume label syntax is incorrect" when attempting to extract Unity packages.

**Fix Implemented:**  
- Added a check to detect and remove invisible Unicode characters in the path before moving extracted files.
- Removed any "00" appended to file extensions (e.g., `.mat00` to `.mat`).
- Included an additional check at the start to search for and remove any invalid path characters.

These changes ensure that the extraction process handles paths correctly and prevents the mentioned error.
